name: svce_student
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  barcode_widget: ^2.0.4
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.gif
    - assets/images/studentavatar.png
    - assets/images/facultyavatar.png
    - assets/images/securityavatar.png
